name: Difftest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone Difftest Repo
        uses: actions/checkout@v3
        with:
          repository: "HITSZ-NSCSCC22/difftest"

      - name: Download NEMU Interpreter
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "HITSZ-NSCSCC22/loongarch32-toolchains"
          file: "la32-nemu-interpreter-so"
          target: "la32-nemu-interpreter-so"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build & Test
        run: make difftest
